---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.name }}
    spec:
      containers:
      - name: nats-mq
        image: {{ .Values.image }}
        imagePullPolicy: Always
        command:
        - /go/bin/nats-mq
        - -c
        - /etc/nats-mq/nats-mq.conf
        volumeMounts:
        - name: config
          mountPath: /etc/nats-mq/
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name }}-conf
